# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Flogo CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      CLIENT_ID: ${{secrets.CLIENT_ID}}
      CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
      APP_ID: 'dnqcj37vr75gcqpwmrg4nthgro5xyuht'
      
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml fetch-token
