# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Flogo CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      CLIENT_ID: ${{secrets.CLIENT_ID}}
      CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
      APP_ID: APP_ID
      APP_JSON: APP_JSON
      EXECUTABLE_NAME: EXECUTABLE_NAME
      TARGET_ARCH: TARGET_ARCH
      TARGET_OS: TARGET_OS
      
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml build-using-appjson download-app  -DCLIENT_ID=$CLIENT_ID -DCLIENT_SECRET=$CLIENT_SECRET -DAPP_ID=$APP_ID -DTARGET_OS=$TARGET_OS -DTARGET_ARCH=$TARGET_ARCH -DEXECUTABLE_NAME=$EXECUTABLE_NAME -DAPP_JSON=$APP_JSON
      
