# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Flogo CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      CLIENT_ID: ${{secrets.CLIENT_ID}}
      CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
      APP_ID: dnqcj37vr75gcqpwmrg4nthgro5xyuht
      APP_JSON: OrderRetrieveOrchestrator.json
      EXECUTABLE_NAME: orderRetrieveOrchestrator
      TARGET_ARCH: amd64
      TARGET_OS: linux
      CONTAINER_NAME: order-retrieve-orchestrator
      CONTAINER_TAG: latest
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
    - name: Building app executable using application json 
      run: ant -noinput -buildfile build.xml build-using-appjson download-app-using-buildid  docker-build DCONTAINER_NAME=$CONTAINER_NAME -DCONTAINER_TAG=$CONTAINER_TAG -DCLIENT_ID=$CLIENT_ID -DCLIENT_SECRET=$CLIENT_SECRET -DAPP_ID=$APP_ID -DTARGET_OS=$TARGET_OS -DTARGET_ARCH=$TARGET_ARCH -DEXECUTABLE_NAME=$EXECUTABLE_NAME -DAPP_JSON=$APP_JSON
