# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Flogo CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      CLIENT_ID: ${{secrets.CLIENT_ID}}
      CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
      REGISTRY_USERNAME: mmussett
      REGISTRY_PASSWORD: f1rest0rm
      REGISTRY_SERVER: registry.vmlab.live
      APP_ID: dnqcj37vr75gcqpwmrg4nthgro5xyuht
      APP_JSON: OrderRetrieveOrchestrator.json
      EXECUTABLE_NAME: orderRetrieveOrchestrator
      TARGET_ARCH: amd64
      TARGET_OS: linux
      SRC_CONTAINER_NAME: order-retrieve-orchestrator
      SRC_CONTAINER_TAG: v1.0.0
      TARGET_CONTAINER_NAME: order-retrieve-orchestrator
      TARGET_CONTAINER_TAG: v1.0.0
      
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4

    - name: Building app executable using application json 
      run: ant -noinput -buildfile build.xml build-using-appjson download-app-using-buildid 

    - name: Building Docker Container Image 
      run: ant -noinput -buildfile build.xml docker-build 
    
    - name: Pushing Docker Container Image to Registry 
      run: ant -noinput -buildfile build.xml docker-push 
